on:
  pull_request:
    paths:
      - '**.rs'
name: Benchmark pull requests
jobs:
  runBenchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: boa-dev/criterion-compare-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branchName: ${{ github.base_ref }}
          features: "wide"
