on:
  push:
    branches:
      - master
    paths:
      - '**.rs'
  pull_request:
    paths:
      - '**.rs'
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

name: Benchmark pull requests
jobs:
  runBenchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v0
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed
      - name: Build the benchmark target(s)
        run: cargo codspeed build -p benchmarks
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v1
        with:
          run: cargo codspeed run
          working-directory: palette # mimics how tests work, so the colors CSV can be found
          token: ${{ secrets.CODSPEED_TOKEN }}
