on:
  push:
    branches:
      - master

name: Publish documentation

jobs:
  documentation:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Generate
        run: cargo doc --package palette --no-deps --all-features
      - name: Upload
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: target/doc
